---
title: C28105 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: mikeblome
ms.author: mblome
manager: jillfra
ms.openlocfilehash: 78fefc8101db0585d4e7fb741dd00ff9473698c8
ms.sourcegitcommit: 8b538eea125241e9d6d8b7297b72a66faa9a4a47
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 01/23/2019
ms.locfileid: "54792680"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Ostrzeżenie C28105: Wyciek zasobów z powodu wyjątku  
  
 Podany zasób nie jest zwalniana, gdy wyjątek jest zgłaszany. Instrukcja określona przez ścieżkę może zgłosić wyjątek. To ostrzeżenie jest podobny do ostrzeżenie [C28103](../code-quality/c28103.md), z tą różnicą, że w tym przypadku chodzi o wyjątku.  
  
## <a name="example"></a>Przykład  
 Poniższy kod generuje to ostrzeżenie:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Poniższy kod pozwala uniknąć tego ostrzeżenia:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```
