---
title: C28105 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
caps.latest.revision: 5
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: c985cc9c4820c02ea427987aca1703beec2e97f1
ms.sourcegitcommit: 6cfffa72af599a9d667249caaaa411bb28ea69fd
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 09/02/2020
ms.locfileid: "77266315"
---
# <a name="c28105"></a>C28105
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Ostrzeżenie C28105: przeciek zasobu z powodu wyjątku  
  
 Określony zasób nie jest zwalniany, gdy zostanie zgłoszony wyjątek. Instrukcja określona przez ścieżkę może zgłosić wyjątek. To ostrzeżenie przypomina [C28103](../code-quality/c28103.md)ostrzegawczy, z tą różnicą, że w tym przypadku występuje wyjątek.  
  
## <a name="example"></a>Przykład  
 Poniższy przykład kodu generuje to ostrzeżenie:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 Poniższy przykład kodu pozwala uniknąć tego ostrzeżenia:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```
