---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 0ecf69db24b9c9d970feb818b0342528e9b840eb
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878050"
---
# <a name="c6318"></a>C6318
Ostrzeżenie C6318: źle zdefiniowana __try/\__except: Użycie stałej EXCEPTION_CONTINUE_SEARCH lub innej stałej, która daje w wyniku zero w wyrażeniu filtru wyjątków. Kod, w bloku obsługi wyjątków, nie jest wykonywany.

 To ostrzeżenie wskazuje, że jeśli wystąpi wyjątek w chronionym bloku tego programu obsługi wyjątków strukturalnych, wyjątek nie zostanie obsłużony, ponieważ stała `EXCECPTION_CONTINUE_SEARCH` jest używana w wyrażeniu filtru wyjątków.

 Ten kod jest odpowiednikiem chronionego bloku bez bloku obsługi wyjątków, ponieważ blok obsługi nie jest wykonywany.

## <a name="example"></a>Przykład
 Poniższy kod generuje to ostrzeżenie:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Aby poprawić to ostrzeżenie, należy użyć następującego kodu:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Zobacz także
 [try-except, instrukcja](/cpp/cpp/try-except-statement)
